### ISSUE TITLE
New Phone, Who dis?

### ISSUE THREAD

**Issue by Madzahttr** [RayzrDev/Gameboi#1]

**Comment by abulujayn** [comment]
discord hack week m'boi

**Comment by Madzahttr** [comment]
🤔 never heard of it

**Comment by abulujayn** [comment]
you didn't get the email? I'll send you a link when I get home

**Comment by Madzahttr** [comment]
Oh i did, i don't check emails often

**Comment by foxfirecodes** [comment]
Irrelevant at this point :smile:
